version: '3'
services:
  backend_prod:
    build:
      context: ./be
      dockerfile: ./Dockerfile-prod
    image: backend_prod
    container_name: backend_prod
    ports:
      - ${BE_PROD_HTTP_PORT}:3000
    environment:
      HTTP_PORT: ${BE_PROD_HTTP_PORT}
    volumes:
      - ./be/src:/usr/app/src
