version: '3'
services:
  server:
    image: calitb/server_prod
    build:
      context: ./be
      dockerfile: ./Dockerfile-prod
    container_name: server_prod
    ports:
      - 80:3000
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
  mysql:
    image: calitb/mysql_prod
    build:
      context: ./db
    container_name: db_prod
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer
    container_name: adminer_prod
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: price
    depends_on:
      - mysql
