version: '3'
services:
  server:
    image: calitb/server_dev
    build:
      context: ./be
    container_name: server_dev
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./be/src:/usr/app/src
    depends_on:
      - mysql
  mysql:
    image: calitb/mysql_dev
    build:
      context: ./db
    container_name: db_dev
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer
    container_name: adminer_dev
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: price
    depends_on:
      - mysql
